### ISSUE TITLE
an update to 10.4.1

### ISSUE THREAD

**Issue by jacfont** [bjwschaap/platformio-libopencm3-freertos#1]
Thanks a lot.
I've been searching on how to achieve this ... and you did it ;-)

I succeed to update to 10.4.1
- copy /source/*.c & /source/include/*.h to your /lib/rtos
- copy Source/portable/GCC/ARM_CM3/* to your /lib/rtos

In the demo file, the 'vApplicationStackOverflowHook' is already defined now in the task.h (with a slightly different definition)

this is the change I did in the demo:

//extern void vApplicationStackOverflowHook(xTaskHandle *pxTask, signed portCHAR *pcTaskName);

void vApplicationStackOverflowHook( TaskHandle_t xTask __attribute__((unused)) ,
                                               char * pcTaskName __attribute__((unused)) )

Thanks for your work.

**Comment by bjwschaap** [comment]
Hi @jacfontaine sorry for my late response. Glad you got it to work!
I'll try and reproduce according to your notes, and update this template.
Thank you for sharing!

**Comment by bjwschaap** [comment]
Hi @jacfontaine just to let you know: I've updated this repo to FreeRTOS 10.4.1 using your instructions. Thank you!
